### ISSUE TITLE
[1.12] Crash on Game Start

### ISSUE THREAD

**Issue by MasterEnderman** [davqvist/Restriction#1]
Forge: 14.23.4.2707
Restriction: 0.1.12
Console Spam: https://pastebin.com/4wPSgtph
Crash Report: https://paste.dimdev.org/genipenese.mccrash
Restriction.json: https://pastebin.com/ts3mi0PC

**Comment by davqvist** [comment]
Your json is malformed. `"amount": 201,` you have an additional comma here. Always make sure that your json is valid. You can use sites like https://jsonformatter.curiousconcept.com/ to do that.

**Comment by MasterEnderman** [comment]
Sorry for the inconvenience.

**Comment by davqvist** [comment]
No worries.

**Comment by MasterEnderman** [comment]
So I removed the additional comma and my game starts fine now. But I still can place the specified block below y-level 201. Is there another mistake i made?
